<?php
require 'vendor/autoload.php'; // Require the autoloader generated by Composer

use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mailer\Transport;
use Symfony\Component\Mime\Email;

// Create the Mailer with the desired transport
$transport = Transport::fromDsn('smtp://username:password@your_smtp_host:port');
$mailer = new Mailer($transport);

// Process the form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get the form data
    $name = $_POST['name'];
    $email = $_POST['email'];
    $subject = $_POST['subject'];
    $message = $_POST['message'];

    // Create the email message
    $email = (new Email())
        ->from($email)
        ->to('your_email@example.com') // Replace with your own email address
        ->subject($subject)
        ->text($message)
        ->html('<p>' . $message . '</p>');

    // Send the email
    $mailer->send($email);

    // Redirect or display a success message
    // Replace the URL with your desired success page or use a success message
    header('Location: success.html');
    exit;
}
?>
